//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShop.Model
{
  using System;
  using System.Collections.Generic;

  public partial class Category
  {
    public Category()
    {
      Products = new HashSet<Product>();
    }

    public int Id { get; set; }

    public string Name { get; set; }

    public int CompanyId { get; set; }

    public Nullable<int> ParentId { get; set; }

    public virtual ICollection<Product> Products { get; set; }
  }
}
