//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int orderItemID { get; set; }
        public int orderID { get; set; }
        public int productID { get; set; }
        public double price { get; set; }
        public byte quantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
