// <auto-generated />
namespace eShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adressfullNameColInAppUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adressfullNameColInAppUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201703081025084_adress-fullNameColInAppUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
